const form = document.querySelector('#settings-form');
const title = document.querySelector('#title');
const subtitle = document.querySelector('#subtitle');
const saveButton = document.querySelector('#save');
const toast = document.querySelector('#toast');
let savedConfig = {};
const descriptions = {assistant:'Local intelligence connection', voice:'Wake word, transcription, and speech', companion:'Corner companion appearance', appearance:'Product visual identity', system:'Desktop integration', sandbox:'Approval and protection controls'};

function message(text, bad = false) { toast.textContent = text; toast.style.background = bad ? '#ffe8e1' : '#e8f8ee'; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3200); }
function updateOutput(input) { const output = document.querySelector(`[data-output="${input.name}"]`); if (output) output.value = input.name === 'wake_word_threshold' ? Number(input.value).toFixed(2) : `${input.value}${input.name === 'avatar_scale' ? '%' : ' sec'}`; }
function brandingValues() { return {brand_name:form.brand_name.value, assistant_name:form.assistant_name.value, logo_path:form.logo_path.value, wallpaper_path:form.wallpaper_path.value, lockscreen_path:form.lockscreen_path.value, icon_theme:form.icon_theme.value, cursor_theme:form.cursor_theme.value, font:form.font.value}; }
function load(data) { savedConfig = data; Object.entries(data).forEach(([name, value]) => { const controls = form.querySelectorAll(`[name="${name}"]`); controls.forEach(control => { if (control.type === 'checkbox') control.checked = Boolean(value); else if (control.type === 'radio') control.checked = control.value === value; else if (name === 'allowed_api_hosts') control.value = value.join('\n'); else control.value = value; updateOutput(control); }); }); const branding = data.branding || {}; Object.entries(branding).forEach(([name, value]) => { if (form.elements[name]) form.elements[name].value = value; }); document.documentElement.style.setProperty('--accent', data.avatar_accent || '#4de3a7'); applyTheme(data.theme); }
function applyTheme(theme) { const themes = {forest:['#101513','#19201d','#202a25','#4de3a7'],graphite:['#121416','#1d2024','#282c31','#8de0c0'],sunrise:['#1b1412','#29201c','#382a24','#f0ad73'],ocean:['#10171b','#19252b','#22333b','#74d6d0']}; const values = themes[theme] || themes.forest; ['--bg','--panel','--panel-2','--accent'].forEach((name,index) => document.documentElement.style.setProperty(name,values[index])); }
function collect() { const data = {}; ['ollama_url','ollama_model','ai_provider','api_key_env','whisper_cli','whisper_model','piper_model','avatar_corner','avatar_accent'].forEach(name => data[name] = form.elements[name].value); data.theme = form.querySelector('[name="theme"]:checked')?.value || 'forest'; ['allow_external_apis','hyprland_enabled','wake_word_enabled','speech_enabled','always_listening_enabled','sandbox_lock_settings','avatar_enabled','avatar_animation_enabled'].forEach(name => data[name] = form.elements[name].checked); data.allowed_api_hosts = form.elements.allowed_api_hosts.value.split('\n').map(item => item.trim()).filter(Boolean); data.wake_word_threshold = Number(form.elements.wake_word_threshold.value); data.voice_command_seconds = Number(form.elements.voice_command_seconds.value); data.avatar_scale = Number(form.elements.avatar_scale.value); data.branding = brandingValues(); return data; }
document.querySelectorAll('.nav-item').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('.nav-item,.settings-section').forEach(item => item.classList.remove('active')); button.classList.add('active'); document.querySelector(`.settings-section[data-section="${button.dataset.section}"]`).classList.add('active'); title.textContent = button.textContent; subtitle.textContent = descriptions[button.dataset.section]; }));
form.addEventListener('input', event => { updateOutput(event.target); if (event.target.name === 'avatar_accent') document.documentElement.style.setProperty('--accent', event.target.value); if (event.target.name === 'theme') applyTheme(event.target.value); });
saveButton.addEventListener('click', async () => { const changes = collect(); const protectedKeys = ['always_listening_enabled','hyprland_enabled','allow_external_apis','ai_provider','ollama_url']; const protectedChange = protectedKeys.some(key => changes[key] !== savedConfig[key]); const confirmation = protectedChange ? (window.confirm('Apply these protected local settings?') ? 'APPLY' : '') : ''; try { const response = await fetch('/api/config', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({changes, confirmation})}); const data = await response.json(); if (!response.ok) throw new Error(data.error); load(data); message('Settings saved'); } catch (error) { message(error.message, true); } });
fetch('/api/config').then(response => response.json()).then(load).catch(() => message('Could not load local settings', true));
