background {
    monitor =
    path = /usr/share/ai-os/wallpapers/lockscreen.png
    blur_passes = 2
    brightness = 0.85
}

input-field {
    monitor =
    size = 300, 56
    position = 0, -120
    dots_center = true
    fade_on_empty = false
    placeholder_text = Password
}
